# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # Base configurations
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
  
    # Web01: Ubuntu server
    config.vm.define "web01" do |web01|
      web01.vm.box = "ubuntu/bionic64"  # Change to a different Ubuntu version if needed
      web01.vm.hostname = "web01"
      web01.vm.network "private_network", ip: "192.168.56.10"
    end
  
    # Web02: Ubuntu server
    config.vm.define "web02" do |web02|
      web02.vm.box = "ubuntu/bionic64"
      web02.vm.hostname = "web02"
      web02.vm.network "private_network", ip: "192.168.56.11"
    end
  
    # DB01: CentOS server
    config.vm.define "db01" do |db01|
      db01.vm.box = "centos/7"
      db01.vm.hostname = "db01"
      db01.vm.network "private_network", ip: "192.168.56.12"
      db01.vm.provision "shell", inline: <<-SHELL
         yum install -y wget unzip mariadb-server
         systemctl start mariadb
         systemctl enable mariadb
         SHELL
    end
  end
  
